### ISSUE TITLE
Build error from version.txt

### ISSUE THREAD

**Issue by chrispy2day** [fastly/remix-compute-js#15]
New to Remix and trying it out following the template, but get a build error.

Steps:
1. npm create remix@latest ./new-app-js -- --template https://github.com/fastly/remix-compute-js/tree/main/packages/remix-template
2. cd new-app-js
3. npm run dev

Output:
ERROR in ./build/version.txt 1:4
Module parse failed: Identifier directly after number (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Like I said, I'm brand new to Remix so I could be missing something obvious, but have not changed anything from the template and could use some direction, thanks!

**Comment by harmony7** [comment]
Thanks for reaching out! We'll take a look at this and give you and update.

**Comment by harmony7** [comment]
Hi! the reason you're having this problem is because this template currently does not support Remix v2.
That's on our list, but for now you can get this to work with Remix v1 by using this command instead:

```
npm create remix@^1 ./new-app-js -- --template https://github.com/fastly/remix-compute-js/tree/main/packages/remix-template
```

(note the `@^1` instead of `@latest`)

I'm going to close this for now, but feel free to reopen if you have any questions.

**Comment by chrispy2day** [comment]
Appreciate the update, thanks!
