### ISSUE TITLE
Live Reload doesn't work for applications generated with this configuration

### ISSUE THREAD

**Issue by daynejones** [fastly/remix-compute-js#6]
I tried it a few times and I believe that if a new app is created using the instructions in the README.md, you get a working application but LiveReload doesn't work as expected. Instead of the page reloading almost instantaneously like I'm used to when working on remixjs sites, the dev server decides to restart entirely and I have to wait a minute or two before my changes can be viewed.

**Comment by daynejones** [comment]
Investigating further, the title may be misleading. It could just be a significantly slower restart than I'm used to. Is it normal for reloads to be slow with Fastly's server runtime?

**Comment by harmony7** [comment]
Hi. thanks for reaching out, and we appreciate your patience!

Yes, the "live reload" isn't as quick as reloading using a node server. This has to do with the way JavaScript programs need to be compiled and built into a Wasm binary and then finally have the Fastly development server relaunch using that binary. 
Every change needs to go through this whole process and it takes a few seconds.

You shouldn't have to wait "a minute or two" though.  Only until the development server restarts, which you should be able to see in your terminal window.

Closing, because this isn't a bug, but if you have any other thoughts please feel free to reach out again.
